=== Redd-15/IRE699_XMLGyak/XMLTaskIRE699/XMLSchemaIRE699.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!--Egyszerű tipusok-->

    <xs:element name="szul_ev" type="xs:integer" />
    <xs:element name="nev" type="xs:string" />
    <xs:element name="tel_szam" type="xs:string" />
    <xs:element name="marka" type="xs:string" />
    <xs:element name="ferohely" type="xs:integer" />
    <xs:element name="fogyasztas" type="xs:integer"/>
    <xs:element name="utvonal_nev" type="xs:string" />
    <xs:element name="tav_elo" type="xs:integer" />
    <xs:element name="sorszam" type="xs:integer" />
    <xs:element name="m_ferohely" type="xs:integer" />
    <xs:element name="varos" type="xs:string" />
    <xs:element name="utca" type="xs:string" />
    <xs:element name="hazszam" type="xs:integer" />

    <xs:element name="uzemanyag" type="uzemanyagTipus"/>
    <xs:element name="rendszam" type="rendszamTipus"/>
    <xs:element name="uzemanyag_szint" type="uzemanyag_szintTipus"/>
    <xs:element name="indulasi_ido" type="indulasi_idoTipus"/>
    <xs:element name="fedett" type="fedettTipus"/>
    <xs:element name="tipus" type="tipusTipus"/>
    
    
    <!--Saját tipusok-->

    <xs:simpleType name="uzemanyagTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Elektromos"/>
            <xs:enumeration value="Dízel"/>
            <xs:enumeration value="Hibrid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rendszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z][A-Z][A-Z]-[0-9][0-9][0-9]"/>
            <xs:pattern value="[A-Z][A-Z][A-Z]-[0-9][0-9][0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="uzemanyag_szintTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="indulasi_idoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9]:[0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fedettTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="N"/>
            <xs:enumeration value="I"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Komplex tipusok-->

    <xs:complexType name="tipusTipus">
        <xs:sequence>
            <xs:element ref="marka"/>
            <xs:element ref="uzemanyag"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="soforTipus">
        <xs:sequence>
            <xs:element ref="szul_ev" maxOccurs="1"/>
            <xs:element ref="tel_szam" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element ref="nev" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="skod" type="xs:integer" use="required" />
        <xs:attribute name="lakhely" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="vezetiTipus">
        <xs:attribute name="sofor" type="xs:integer" use="required" />
        <xs:attribute name="busz" type="xs:integer" use="required" />
    </xs:complexType>
    
    <xs:complexType name="buszTipus">
        <xs:sequence>
            <xs:element ref="tipus" maxOccurs="1"/>
            <xs:element ref="ferohely" maxOccurs="1"/>
            <xs:element ref="rendszam" maxOccurs="1"/>
            <xs:element ref="uzemanyag_szint" maxOccurs="1"/>
            <xs:element ref="fogyasztas" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="bkod" type="xs:integer" use="required" />
        <xs:attribute name="jarat" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="jaratTipus">
        <xs:sequence>
            <xs:element ref="indulasi_ido"/>
        </xs:sequence>
        <xs:attribute name="jkod" type="xs:integer" use="required" />
        <xs:attribute name="utvonal" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="utvonalTipus">
        <xs:sequence>
            <xs:element ref="utvonal_nev" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="utkod" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="megallasTipus">
        <xs:sequence>
            <xs:element ref="tav_elo" maxOccurs="1"/>
            <xs:element ref="sorszam" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="utvonal" type="xs:integer" use="required" />
        <xs:attribute name="megallo" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="megalloTipus">
        <xs:sequence>
            <xs:element ref="fedett" maxOccurs="1"/>
            <xs:element ref="m_ferohely" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="mkod" type="xs:integer" use="required" />
        <xs:attribute name="helyszin" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="helyszinTipus">
        <xs:sequence>
            <xs:element ref="varos" maxOccurs="1"/>
            <xs:element ref="utca" maxOccurs="1"/>
            <xs:element ref="hazszam" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="hkod" type="xs:integer" use="required" />
    </xs:complexType>

    <!--Gyökérelem elemei-->

    <xs:element name="MVK_database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sofor" type="soforTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Vezeti" type="vezetiTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Busz" type="buszTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Jarat" type="jaratTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Utvonal" type="utvonalTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Megallas" type="megallasTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Megallo" type="megalloTipus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Helyszin" type="helyszinTipus" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    

    <!--Elsődleges kulcsok-->

        <xs:key name="Sofor_kod">
            <xs:selector xpath="Sofor"/>
            <xs:field xpath="@skod"/>
        </xs:key>
        <xs:key name="Busz_kod">
            <xs:selector xpath="Busz"/>
            <xs:field xpath="@bkod"/>
        </xs:key>
        <xs:key name="Jarat_kod">
            <xs:selector xpath="Jarat"/>
            <xs:field xpath="@jkod"/>
        </xs:key>
        <xs:key name="Utvonal_kod">
            <xs:selector xpath="Utvonal"/>
            <xs:field xpath="@utkod"/>
        </xs:key>
        <xs:key name="Megallo_kod">
            <xs:selector xpath="Megallo"/>
            <xs:field xpath="@mkod"/>
        </xs:key>
        <xs:key name="Helyszin_kod">
            <xs:selector xpath="Helyszin"/>
            <xs:field xpath="@hkod"/>
        </xs:key>

        <!--Idegen kulcsok-->

        <xs:keyref name="Lakhely_kulcs" refer="Helyszin_kod">
            <xs:selector xpath="Sofor"/>
            <xs:field xpath="@lakhely"/>
        </xs:keyref>
        <xs:keyref name="Vezeto_kulcs" refer="Sofor_kod">
            <xs:selector xpath="Vezeti"/>
            <xs:field xpath="@sofor"/>
        </xs:keyref>
        <xs:keyref name="Busz_kulcs" refer="Busz_kod">
            <xs:selector xpath="Vezeti"/>
            <xs:field xpath="@busz"/>
        </xs:keyref>
        <xs:keyref name="Jarat_kulcs" refer="Jarat_kod">
            <xs:selector xpath="Busz"/>
            <xs:field xpath="@jarat"/>
        </xs:keyref>
        <xs:keyref name="Utvonal_jarat_kulcs" refer="Utvonal_kod">
            <xs:selector xpath="Jarat"/>
            <xs:field xpath="@utvonal"/>
        </xs:keyref>
        <xs:keyref name="Utvonal_megallas_kulcs" refer="Utvonal_kod">
            <xs:selector xpath="Megallas"/>
            <xs:field xpath="@utvonal"/>
        </xs:keyref>
        <xs:keyref name="Megallo_kulcs" refer="Megallo_kod">
            <xs:selector xpath="Megallas"/>
            <xs:field xpath="@megallo"/>
        </xs:keyref>
        <xs:keyref name="Helyszin_kulcs" refer="Helyszin_kod">
            <xs:selector xpath="Megallo"/>
            <xs:field xpath="@helyszin"/>
        </xs:keyref>

        <!-- Az 1:1 kapcsolatok megvalósitása-->

        <xs:unique name="Megallo_Helyszin_egyegy">
            <xs:selector xpath="Megallo"/>
            <xs:field xpath="@helyszin"/>
        </xs:unique>
        <xs:unique name="Sofor_Helyszin_egyegy">
            <xs:selector xpath="Sofor"/>
            <xs:field xpath="@lakhely"/>
        </xs:unique>

    </xs:element>
</xs:schema>

=== Redd-15/IRE699_XMLGyak/XMLTaskIRE699/XMLIRE699.xml
<?xml version="1.0" encoding="UTF-8"?>

<MVK_database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaIRE699.xsd">

    <!--Sofőrök-->

    <Sofor skod="1" lakhely="1">
        <szul_ev>1980</szul_ev>
        <tel_szam>+36301234566</tel_szam>
        <tel_szam>+36701234566</tel_szam>
        <nev>Nagy József</nev>
    </Sofor>

    <Sofor skod="2" lakhely="2">
        <szul_ev>1976</szul_ev>
        <tel_szam>+36301235466</tel_szam>
        <tel_szam>+36401232366</tel_szam>
        <nev>Kiss János</nev>
    </Sofor>

    <Sofor skod="3" lakhely="3">
        <szul_ev>1999</szul_ev>
        <tel_szam>+363012764566</tel_szam>
        <tel_szam>+36301267566</tel_szam>
        <nev>Adorján István</nev>
    </Sofor>

    <!--Mely sofőr mely buszt vezeti-->

    <Vezeti sofor="1" busz="2"/>
    <Vezeti sofor="2" busz="3"/>
    <Vezeti sofor="3" busz="1"/>

    <!--Buszok-->

    <Busz bkod="1" jarat="3">
        <tipus>
            <marka>BYD</marka>
            <uzemanyag>Elektromos</uzemanyag>
        </tipus>
        <ferohely>145</ferohely>
        <rendszam>AABC-123</rendszam>
        <uzemanyag_szint>80</uzemanyag_szint>
        <fogyasztas>30</fogyasztas>
    </Busz>

    <Busz bkod="2" jarat="2">
        <tipus>
            <marka>BYD</marka>
            <uzemanyag>Elektromos</uzemanyag>
        </tipus>
        <ferohely>145</ferohely>
        <rendszam>AABC-133</rendszam>
        <uzemanyag_szint>74</uzemanyag_szint>
        <fogyasztas>30</fogyasztas>
    </Busz>

    <Busz bkod="3" jarat="1">
        <tipus>
            <marka>MAN</marka>
            <uzemanyag>Dízel</uzemanyag>
        </tipus>
        <ferohely>110</ferohely>
        <rendszam>AABC-143</rendszam>
        <uzemanyag_szint>20</uzemanyag_szint>
        <fogyasztas>12</fogyasztas>
    </Busz>

    <!--Járatok-->

    <Jarat jkod="1" utvonal="3">
        <indulasi_ido>10:00</indulasi_ido>
    </Jarat>

    <Jarat jkod="2" utvonal="2">
        <indulasi_ido>15:00</indulasi_ido>
    </Jarat>

    <Jarat jkod="3" utvonal="1">
        <indulasi_ido>18:20</indulasi_ido>
    </Jarat>

    <!--Útvonalak-->

    <Utvonal utkod="1">
        <utvonal_nev>1A</utvonal_nev>
    </Utvonal>

    <Utvonal utkod="2">
        <utvonal_nev>2</utvonal_nev>
    </Utvonal>

    <Utvonal utkod="3">
        <utvonal_nev>3A</utvonal_nev>
    </Utvonal>

    <!--Az egyes útvonalak megállói-->
        <!--3A-->

    <Megallas utvonal="3" megallo="3">
        <tav_elo>10</tav_elo>
        <sorszam>1</sorszam>
    </Megallas>

    <Megallas utvonal="3" megallo="1">
        <tav_elo>5</tav_elo>
        <sorszam>2</sorszam>
    </Megallas>

    <Megallas utvonal="3" megallo="4">
        <tav_elo>1</tav_elo>
        <sorszam>3</sorszam>
    </Megallas>

        <!--2-->

    <Megallas utvonal="2" megallo="2">
        <tav_elo>8</tav_elo>
        <sorszam>1</sorszam>
    </Megallas>

    <Megallas utvonal="2" megallo="6">
        <tav_elo>25</tav_elo>
        <sorszam>2</sorszam>
    </Megallas>

    <Megallas utvonal="2" megallo="3">
        <tav_elo>30</tav_elo>
        <sorszam>3</sorszam>
    </Megallas>

        <!--1A-->

    <Megallas utvonal="1" megallo="5">
        <tav_elo>15</tav_elo>
        <sorszam>1</sorszam>
    </Megallas>

    <Megallas utvonal="1" megallo="3">
        <tav_elo>19</tav_elo>
        <sorszam>2</sorszam>
    </Megallas>
    
    <Megallas utvonal="1" megallo="2">
        <tav_elo>8</tav_elo>
        <sorszam>3</sorszam>
    </Megallas>

    <!--Megállók-->

    <Megallo mkod="1" helyszin="4">
        <fedett>I</fedett>
        <m_ferohely>10</m_ferohely>
    </Megallo>

    <Megallo mkod="2" helyszin="9">
        <fedett>N</fedett>
        <m_ferohely>50</m_ferohely>
    </Megallo>

    <Megallo mkod="3" helyszin="6">
        <fedett>N</fedett>
        <m_ferohely>70</m_ferohely>
    </Megallo>

    <Megallo mkod="4" helyszin="5">
        <fedett>I</fedett>
        <m_ferohely>12</m_ferohely>
    </Megallo>

    <Megallo mkod="5" helyszin="7">
        <fedett>I</fedett>
        <m_ferohely>55</m_ferohely>
    </Megallo>

    <Megallo mkod="6" helyszin="8">
        <fedett>N</fedett>
        <m_ferohely>30</m_ferohely>
    </Megallo>

    <!--Helyszínek-->

    <Helyszin hkod="1">
        <varos>Miskolc</varos>
        <utca>Ady Endre</utca>
        <hazszam>10</hazszam>
    </Helyszin>

    <Helyszin hkod="2">
        <varos>Mályi</varos>
        <utca>Fő</utca>
        <hazszam>17</hazszam>
    </Helyszin>

    <Helyszin hkod="3">
        <varos>Miskolc</varos>
        <utca>Széchenyi János</utca>
        <hazszam>34</hazszam>
    </Helyszin>

    <Helyszin hkod="4">
        <varos>Miskolc</varos>
        <utca>Balaton</utca>
        <hazszam>170</hazszam>
    </Helyszin>

    <Helyszin hkod="5">
        <varos>Miskolc</varos>
        <utca>Balaton</utca>
        <hazszam>1</hazszam>
    </Helyszin>

    <Helyszin hkod="6">
        <varos>Miskolc</varos>
        <utca>Tiszai-PU</utca>
        <hazszam>1</hazszam>
    </Helyszin>

    <Helyszin hkod="7">
        <varos>Miskolc</varos>
        <utca>Egyetem</utca>
        <hazszam>1</hazszam>
    </Helyszin>

    <Helyszin hkod="8">
        <varos>Miskolc</varos>
        <utca>Reptéri</utca>
        <hazszam>11</hazszam>
    </Helyszin>

    <Helyszin hkod="9">
        <varos>Miskolc</varos>
        <utca>Széchenyi János</utca>
        <hazszam>1</hazszam>
    </Helyszin>


</MVK_database>

=== Redd-15/IRE699_XMLGyak/XMLTaskIRE699/XMLIRE699S.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><MVK_database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaIRE699.xsd">

    <!--Sofőrök-->

    <Sofor lakhely="1" skod="1">
        <szul_ev>1980</szul_ev>
        <tel_szam>+36301234566</tel_szam>
        <tel_szam>+36701234566</tel_szam>
        <nev>Nagy József</nev>
    </Sofor>

    <Sofor lakhely="2" skod="2">
        <szul_ev>1976</szul_ev>
        <tel_szam>+36301235466</tel_szam>
        <tel_szam>+36401232366</tel_szam>
        <nev>Kiss János</nev>
    </Sofor>

    <Sofor lakhely="3" skod="3">
        <szul_ev>1999</szul_ev>
        <tel_szam>+363012764566</tel_szam>
        <tel_szam>+36301267566</tel_szam>
        <nev>Adorján István</nev>
    </Sofor>

    <!--Mely sofőr mely buszt vezeti-->

    <Vezeti busz="2" sofor="1"/>
    <Vezeti busz="3" sofor="2"/>
    <Vezeti busz="1" sofor="3"/>

    <!--Buszok-->

    <Busz bkod="1" jarat="3">
        <tipus>
            <marka>BYD</marka>
            <uzemanyag>Elektromos</uzemanyag>
        </tipus>
        <ferohely>145</ferohely>
        <rendszam>AABC-123</rendszam>
        <uzemanyag_szint>80</uzemanyag_szint>
        <fogyasztas>30</fogyasztas>
    </Busz>

    <Busz bkod="2" jarat="2">
        <tipus>
            <marka>BYD</marka>
            <uzemanyag>Elektromos</uzemanyag>
        </tipus>
        <ferohely>145</ferohely>
        <rendszam>AABC-133</rendszam>
        <uzemanyag_szint>74</uzemanyag_szint>
        <fogyasztas>30</fogyasztas>
    </Busz>

    <Busz bkod="3" jarat="1">
        <tipus>
            <marka>MAN</marka>
            <uzemanyag>Dízel</uzemanyag>
        </tipus>
        <ferohely>110</ferohely>
        <rendszam>AABC-143</rendszam>
        <uzemanyag_szint>20</uzemanyag_szint>
        <fogyasztas>12</fogyasztas>
    </Busz>

    <!--Járatok-->

    <Jarat jkod="1" utvonal="3">
        <indulasi_ido>10:00</indulasi_ido>
    </Jarat>

    <Jarat jkod="2" utvonal="2">
        <indulasi_ido>15:00</indulasi_ido>
    </Jarat>

    <Jarat jkod="3" utvonal="1">
        <indulasi_ido>18:20</indulasi_ido>
    </Jarat>

    <!--Útvonalak-->

    <Utvonal utkod="1">
        <utvonal_nev>1A</utvonal_nev>
    </Utvonal>

    <Utvonal utkod="2">
        <utvonal_nev>2</utvonal_nev>
    </Utvonal>

    <Utvonal utkod="3">
        <utvonal_nev>3A</utvonal_nev>
    </Utvonal>

    <!--Az egyes útvonalak megállói-->
    <!--3A-->

    <Megallas megallo="3" utvonal="3">
        <tav_elo>10</tav_elo>
        <sorszam>1</sorszam>
    </Megallas>

    <Megallas megallo="1" utvonal="3">
        <tav_elo>5</tav_elo>
        <sorszam>2</sorszam>
    </Megallas>

    <Megallas megallo="4" utvonal="3">
        <tav_elo>1</tav_elo>
        <sorszam>3</sorszam>
    </Megallas>

    <!--2-->

    <Megallas megallo="2" utvonal="2">
        <tav_elo>8</tav_elo>
        <sorszam>1</sorszam>
    </Megallas>

    <Megallas megallo="6" utvonal="2">
        <tav_elo>25</tav_elo>
        <sorszam>2</sorszam>
    </Megallas>

    <Megallas megallo="3" utvonal="2">
        <tav_elo>30</tav_elo>
        <sorszam>3</sorszam>
    </Megallas>

    <!--1A-->

    <Megallas megallo="5" utvonal="1">
        <tav_elo>15</tav_elo>
        <sorszam>1</sorszam>
    </Megallas>

    <Megallas megallo="3" utvonal="1">
        <tav_elo>19</tav_elo>
        <sorszam>2</sorszam>
    </Megallas>

    <Megallas megallo="2" utvonal="1">
        <tav_elo>8</tav_elo>
        <sorszam>3</sorszam>
    </Megallas>

    <!--Megállók-->

    <Megallo helyszin="4" mkod="1">
        <fedett>I</fedett>
        <m_ferohely>10</m_ferohely>
    </Megallo>

    <Megallo helyszin="9" mkod="2">
        <fedett>N</fedett>
        <m_ferohely>50</m_ferohely>
    </Megallo>

    <Megallo helyszin="6" mkod="3">
        <fedett>N</fedett>
        <m_ferohely>70</m_ferohely>
    </Megallo>

    <Megallo helyszin="5" mkod="4">
        <fedett>I</fedett>
        <m_ferohely>12</m_ferohely>
    </Megallo>

    <Megallo helyszin="7" mkod="5">
        <fedett>I</fedett>
        <m_ferohely>55</m_ferohely>
    </Megallo>

    <Megallo helyszin="8" mkod="6">
        <fedett>N</fedett>
        <m_ferohely>30</m_ferohely>
    </Megallo>

    <!--Helyszínek-->

    <Helyszin hkod="1">
        <varos>Miskolc</varos>
        <utca>Ady Endre</utca>
        <hazszam>10</hazszam>
    </Helyszin>

    <Helyszin hkod="2">
        <varos>Mályi</varos>
        <utca>Fő</utca>
        <hazszam>17</hazszam>
    </Helyszin>

    <Helyszin hkod="3">
        <varos>Miskolc</varos>
        <utca>Széchenyi János</utca>
        <hazszam>34</hazszam>
    </Helyszin>

    <Helyszin hkod="4">
        <varos>Miskolc</varos>
        <utca>Balaton</utca>
        <hazszam>170</hazszam>
    </Helyszin>

    <Helyszin hkod="5">
        <varos>Miskolc</varos>
        <utca>Balaton</utca>
        <hazszam>1</hazszam>
    </Helyszin>

    <Helyszin hkod="6">
        <varos>Miskolc</varos>
        <utca>Tiszai-PU</utca>
        <hazszam>1</hazszam>
    </Helyszin>

    <Helyszin hkod="7">
        <varos>Miskolc</varos>
        <utca>Egyetem</utca>
        <hazszam>1</hazszam>
    </Helyszin>

    <Helyszin hkod="8">
        <varos>Miskolc</varos>
        <utca>Reptéri</utca>
        <hazszam>11</hazszam>
    </Helyszin>

    <Helyszin hkod="9">
        <varos>Miskolc</varos>
        <utca>Széchenyi János</utca>
        <hazszam>1</hazszam>
    </Helyszin>


</MVK_database>
